/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import Foundation

import Thrift


public final class AdSlot {

  public var x: Int32

  public var y: Int32

  public var height: Int32?

  public var width: Int32?


  public init(x: Int32, y: Int32) {
    self.x = x
    self.y = y
  }

  public init(x: Int32, y: Int32, height: Int32?, width: Int32?) {
    self.x = x
    self.y = y
    self.height = height
    self.width = width
  }

}

public final class Topic {

  public var id: String


  public init(id: String) {
    self.id = id
  }

}

public final class Image {

  public var url: String

  public var caption: String?

  public var credit: String?


  public init(url: String) {
    self.url = url
  }

  public init(url: String, caption: String?, credit: String?) {
    self.url = url
    self.caption = caption
    self.credit = credit
  }

}

public final class Epic {

  public var title: String

  public var body: String

  public var firstButton: String

  public var secondButton: String?


  public init(title: String, body: String, firstButton: String) {
    self.title = title
    self.body = body
    self.firstButton = firstButton
  }

  public init(title: String, body: String, firstButton: String, secondButton: String?) {
    self.title = title
    self.body = body
    self.firstButton = firstButton
    self.secondButton = secondButton
  }

}

public final class MaybeEpic {

  public var epic: Epic?


  public init() { }
  public init(epic: Epic?) {
    self.epic = epic
  }

}

public protocol Native {

  ///
  /// - Returns: Int32
  /// - Throws: 
  func nativeThriftPackageVersion() throws -> Int32

  ///
  /// - Parameters:
  ///   - adSlots: 
  /// - Throws: 
  func insertAdverts(adSlots: TList<AdSlot>) throws

  ///
  /// - Parameters:
  ///   - adSlots: 
  /// - Throws: 
  func updateAdverts(adSlots: TList<AdSlot>) throws

  ///
  /// - Throws: 
  func launchFrictionScreen() throws

  ///
  /// - Parameters:
  ///   - topic: 
  /// - Throws: 
  func follow(topic: Topic) throws

  ///
  /// - Parameters:
  ///   - topic: 
  /// - Throws: 
  func unfollow(topic: Topic) throws

  ///
  /// - Parameters:
  ///   - images: 
  ///   - selectedIndex: 
  /// - Throws: 
  func launchSlideshow(images: TList<Image>, selectedIndex: Int32) throws

  ///
  /// - Parameters:
  ///   - topic: 
  /// - Returns: Bool
  /// - Throws: 
  func isFollowing(topic: Topic) throws -> Bool

  ///
  /// - Returns: Bool
  /// - Throws: 
  func isPremiumUser() throws -> Bool

  ///
  /// - Returns: MaybeEpic
  /// - Throws: 
  func getEpics() throws -> MaybeEpic

  ///
  /// - Throws: 
  func epicSeen() throws

  ///
  /// - Throws: 
  func test() throws

}

open class NativeClient : TClient /* , Native */ {

}

public protocol NativeAsync {

  ///
  ///   - completion: TAsyncResult<Int32> wrapping return and following Exceptions: 
  func nativeThriftPackageVersion(completion: @escaping (TAsyncResult<Int32>) -> Void)

  ///
  /// - Parameters:
  ///   - adSlots: 
  ///   - completion: TAsyncResult<Void> wrapping return and following Exceptions: 
  func insertAdverts(adSlots: TList<AdSlot>, completion: @escaping (TAsyncResult<Void>) -> Void)

  ///
  /// - Parameters:
  ///   - adSlots: 
  ///   - completion: TAsyncResult<Void> wrapping return and following Exceptions: 
  func updateAdverts(adSlots: TList<AdSlot>, completion: @escaping (TAsyncResult<Void>) -> Void)

  ///
  ///   - completion: TAsyncResult<Void> wrapping return and following Exceptions: 
  func launchFrictionScreen(completion: @escaping (TAsyncResult<Void>) -> Void)

  ///
  /// - Parameters:
  ///   - topic: 
  ///   - completion: TAsyncResult<Void> wrapping return and following Exceptions: 
  func follow(topic: Topic, completion: @escaping (TAsyncResult<Void>) -> Void)

  ///
  /// - Parameters:
  ///   - topic: 
  ///   - completion: TAsyncResult<Void> wrapping return and following Exceptions: 
  func unfollow(topic: Topic, completion: @escaping (TAsyncResult<Void>) -> Void)

  ///
  /// - Parameters:
  ///   - images: 
  ///   - selectedIndex: 
  ///   - completion: TAsyncResult<Void> wrapping return and following Exceptions: 
  func launchSlideshow(images: TList<Image>, selectedIndex: Int32, completion: @escaping (TAsyncResult<Void>) -> Void)

  ///
  /// - Parameters:
  ///   - topic: 
  ///   - completion: TAsyncResult<Bool> wrapping return and following Exceptions: 
  func isFollowing(topic: Topic, completion: @escaping (TAsyncResult<Bool>) -> Void)

  ///
  ///   - completion: TAsyncResult<Bool> wrapping return and following Exceptions: 
  func isPremiumUser(completion: @escaping (TAsyncResult<Bool>) -> Void)

  ///
  ///   - completion: TAsyncResult<MaybeEpic> wrapping return and following Exceptions: 
  func getEpics(completion: @escaping (TAsyncResult<MaybeEpic>) -> Void)

  ///
  ///   - completion: TAsyncResult<Void> wrapping return and following Exceptions: 
  func epicSeen(completion: @escaping (TAsyncResult<Void>) -> Void)

  ///
  ///   - completion: TAsyncResult<Void> wrapping return and following Exceptions: 
  func test(completion: @escaping (TAsyncResult<Void>) -> Void)

}

open class NativeProcessor /* Native */ {

  typealias ProcessorHandlerDictionary = [String: (Int32, TProtocol, TProtocol, Native) throws -> Void]

  public var service: Native

  public required init(service: Native) {
    self.service = service
  }

}

open class NativeProcessorAsync /* Native */ {

  typealias ProcessorHandlerDictionary = [String: (Int32, TProtocol, TProtocol, NativeAsync) throws -> Void]

  public var service: NativeAsync

  public required init(service: NativeAsync) {
    self.service = service
  }

}


