/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import Foundation

import Thrift


fileprivate final class Webview_webviewThriftPackage_args {


  fileprivate init() { }
}

fileprivate func ==(lhs: Webview_webviewThriftPackage_args, rhs: Webview_webviewThriftPackage_args) -> Bool {
  return true
}

extension Webview_webviewThriftPackage_args : Hashable {

  fileprivate var hashValue : Int {
    return 31
  }

}

extension Webview_webviewThriftPackage_args : TStruct {

  fileprivate static var fieldIds: [String: Int32] {
    return [:]
  }

  fileprivate static var structName: String { return "Webview_webviewThriftPackage_args" }

  fileprivate static func read(from proto: TProtocol) throws -> Webview_webviewThriftPackage_args {
    _ = try proto.readStructBegin()

    fields: while true {

      let (_, fieldType, fieldID) = try proto.readFieldBegin()

      switch (fieldID, fieldType) {
        case (_, .stop):            break fields
        case let (_, unknownType):  try proto.skip(type: unknownType)
      }

      try proto.readFieldEnd()
    }

    try proto.readStructEnd()

    return Webview_webviewThriftPackage_args()
  }

}



fileprivate final class Webview_webviewThriftPackage_result {

  fileprivate var success: Int32?


  fileprivate init() { }
  fileprivate init(success: Int32?) {
    self.success = success
  }

}

fileprivate func ==(lhs: Webview_webviewThriftPackage_result, rhs: Webview_webviewThriftPackage_result) -> Bool {
  return
    (lhs.success == rhs.success)
}

extension Webview_webviewThriftPackage_result : Hashable {

  fileprivate var hashValue : Int {
    let prime = 31
    var result = 1
    result = prime &* result &+ (success?.hashValue ?? 0)
    return result
  }

}

extension Webview_webviewThriftPackage_result : TStruct {

  fileprivate static var fieldIds: [String: Int32] {
    return ["success": 0, ]
  }

  fileprivate static var structName: String { return "Webview_webviewThriftPackage_result" }

  fileprivate static func read(from proto: TProtocol) throws -> Webview_webviewThriftPackage_result {
    _ = try proto.readStructBegin()
    var success: Int32?

    fields: while true {

      let (_, fieldType, fieldID) = try proto.readFieldBegin()

      switch (fieldID, fieldType) {
        case (_, .stop):            break fields
        case (0, .i32):             success = try Int32.read(from: proto)
        case let (_, unknownType):  try proto.skip(type: unknownType)
      }

      try proto.readFieldEnd()
    }

    try proto.readStructEnd()

    return Webview_webviewThriftPackage_result(success: success)
  }

}



fileprivate final class Webview_updateFontSize_args {

  fileprivate var size: Int32


  fileprivate init(size: Int32) {
    self.size = size
  }

}

fileprivate func ==(lhs: Webview_updateFontSize_args, rhs: Webview_updateFontSize_args) -> Bool {
  return
    (lhs.size == rhs.size)
}

extension Webview_updateFontSize_args : Hashable {

  fileprivate var hashValue : Int {
    let prime = 31
    var result = 1
    result = prime &* result &+ (size.hashValue)
    return result
  }

}

extension Webview_updateFontSize_args : TStruct {

  fileprivate static var fieldIds: [String: Int32] {
    return ["size": 1, ]
  }

  fileprivate static var structName: String { return "Webview_updateFontSize_args" }

  fileprivate static func read(from proto: TProtocol) throws -> Webview_updateFontSize_args {
    _ = try proto.readStructBegin()
    var size: Int32!

    fields: while true {

      let (_, fieldType, fieldID) = try proto.readFieldBegin()

      switch (fieldID, fieldType) {
        case (_, .stop):            break fields
        case (1, .i32):             size = try Int32.read(from: proto)
        case let (_, unknownType):  try proto.skip(type: unknownType)
      }

      try proto.readFieldEnd()
    }

    try proto.readStructEnd()
    // Required fields
    try proto.validateValue(size, named: "size")

    return Webview_updateFontSize_args(size: size)
  }

}



fileprivate final class Webview_updateFontSize_result {


  fileprivate init() { }
}

fileprivate func ==(lhs: Webview_updateFontSize_result, rhs: Webview_updateFontSize_result) -> Bool {
  return true
}

extension Webview_updateFontSize_result : Hashable {

  fileprivate var hashValue : Int {
    return 31
  }

}

extension Webview_updateFontSize_result : TStruct {

  fileprivate static var fieldIds: [String: Int32] {
    return [:]
  }

  fileprivate static var structName: String { return "Webview_updateFontSize_result" }

  fileprivate static func read(from proto: TProtocol) throws -> Webview_updateFontSize_result {
    _ = try proto.readStructBegin()

    fields: while true {

      let (_, fieldType, fieldID) = try proto.readFieldBegin()

      switch (fieldID, fieldType) {
        case (_, .stop):            break fields
        case let (_, unknownType):  try proto.skip(type: unknownType)
      }

      try proto.readFieldEnd()
    }

    try proto.readStructEnd()

    return Webview_updateFontSize_result()
  }

}



extension WebviewClient : Webview {

  private func send_webviewThriftPackage() throws {
    try outProtocol.writeMessageBegin(name: "webviewThriftPackage", type: .call, sequenceID: 0)
    let args = Webview_webviewThriftPackage_args()
    try args.write(to: outProtocol)
    try outProtocol.writeMessageEnd()
  }

  private func recv_webviewThriftPackage() throws -> Int32 {
    try inProtocol.readResultMessageBegin() 
    let result = try Webview_webviewThriftPackage_result.read(from: inProtocol)
    try inProtocol.readMessageEnd()

    if let success = result.success {
      return success
    }
    throw TApplicationError(error: .missingResult(methodName: "webviewThriftPackage"))
  }

  public func webviewThriftPackage() throws -> Int32 {
    try send_webviewThriftPackage()
    try outProtocol.transport.flush()
    return try recv_webviewThriftPackage()
  }

  private func send_updateFontSize(size: Int32) throws {
    try outProtocol.writeMessageBegin(name: "updateFontSize", type: .call, sequenceID: 0)
    let args = Webview_updateFontSize_args(size: size)
    try args.write(to: outProtocol)
    try outProtocol.writeMessageEnd()
  }

  private func recv_updateFontSize() throws {
    try inProtocol.readResultMessageBegin() 
    _ = try Webview_updateFontSize_result.read(from: inProtocol)
    try inProtocol.readMessageEnd()

  }

  public func updateFontSize(size: Int32) throws {
    try send_updateFontSize(size: size)
    try outProtocol.transport.flush()
    try recv_updateFontSize()
  }

}

extension WebviewProcessor : TProcessor {

  static let processorHandlers: ProcessorHandlerDictionary = {

    var processorHandlers = ProcessorHandlerDictionary()

    processorHandlers["webviewThriftPackage"] = { sequenceID, inProtocol, outProtocol, handler in

      let args = try Webview_webviewThriftPackage_args.read(from: inProtocol)

      try inProtocol.readMessageEnd()

      var result = Webview_webviewThriftPackage_result()
      do {
        result.success = try handler.webviewThriftPackage()
      }
      catch let error { throw error }

      try outProtocol.writeMessageBegin(name: "webviewThriftPackage", type: .reply, sequenceID: sequenceID)
      try result.write(to: outProtocol)
      try outProtocol.writeMessageEnd()
    }
    processorHandlers["updateFontSize"] = { sequenceID, inProtocol, outProtocol, handler in

      let args = try Webview_updateFontSize_args.read(from: inProtocol)

      try inProtocol.readMessageEnd()

      var result = Webview_updateFontSize_result()
      do {
        try handler.updateFontSize(size: args.size)
      }
      catch let error { throw error }

      try outProtocol.writeMessageBegin(name: "updateFontSize", type: .reply, sequenceID: sequenceID)
      try result.write(to: outProtocol)
      try outProtocol.writeMessageEnd()
    }
    return processorHandlers
  }()

  public func process(on inProtocol: TProtocol, outProtocol: TProtocol) throws {

    let (messageName, _, sequenceID) = try inProtocol.readMessageBegin()

    if let processorHandler = WebviewProcessor.processorHandlers[messageName] {
      do {
        try processorHandler(sequenceID, inProtocol, outProtocol, service)
      }
      catch let error as TApplicationError {
        try outProtocol.writeException(messageName: messageName, sequenceID: sequenceID, ex: error)
      }
    }
    else {
      try inProtocol.skip(type: .struct)
      try inProtocol.readMessageEnd()
      let ex = TApplicationError(error: .unknownMethod(methodName: messageName))
      try outProtocol.writeException(messageName: messageName, sequenceID: sequenceID, ex: ex)
    }
  }
}

