/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import Foundation

import Thrift


public final class Epic {

  public var title: String

  public var body: String

  public var firstButton: String

  public var secondButton: String?


  public init(title: String, body: String, firstButton: String) {
    self.title = title
    self.body = body
    self.firstButton = firstButton
  }

  public init(title: String, body: String, firstButton: String, secondButton: String?) {
    self.title = title
    self.body = body
    self.firstButton = firstButton
    self.secondButton = secondButton
  }

}

public protocol Webview {

  ///
  /// - Returns: Int32
  /// - Throws: 
  func webviewThriftPackage() throws -> Int32

  ///
  /// - Parameters:
  ///   - epic: 
  /// - Throws: 
  func insertEpic(epic: Epic) throws

  ///
  /// - Parameters:
  ///   - size: 
  /// - Throws: 
  func updateFontSize(size: Int32) throws

}

open class WebviewClient : TClient /* , Webview */ {

}

open class WebviewProcessor /* Webview */ {

  typealias ProcessorHandlerDictionary = [String: (Int32, TProtocol, TProtocol, Webview) throws -> Void]

  public var service: Webview

  public required init(service: Webview) {
    self.service = service
  }

}


